### ISSUE TITLE
Alternative to Playstore

### ISSUE THREAD

**Issue by IzzySoft** [cubei/flashcards#10]
Would you mind offering your app outside of playstore – e.g. via [F-Droid](https://f-droid.org/) or attaching it to your `releases/` (if you create tags)?

**Comment by cubei** [comment]
Maybe I'm just stupid, but the F-Droid instructions say I need to install something, but there is no link for me to click and the screenshots are so small and there is no button to enlarge them:
https://f-droid.org/en/tutorials/create-repo/

Sorry, but then I don't use that...

What do you mean by tags?

**Comment by IzzySoft** [comment]
That's if you want to create your own repo. The official F-Droid repo builds apps from their sources (ie. they'd pull your repo to build the app themselves, sign them and publish them in their repo). If you're interested, I could help bring your app there (disclosure: I'm one of the F-Droid maintainers). The process takes a little, initially (can be several weeks or just a few days). Until then, I could host your app in [my repo](https://apt.izzysoft.de/fdroid) – but for that I'd need the APK, preferably via the [`releases/`](https://github.com/cubei/flashcards/releases) page (where you also find out what is meant by tags, namely the result of `git tag`) or alternatively from inside your repo. Just let me know!

PS: Using tags is generally a good idea to mark releases – and would enable F-Droid to automatically detect updates.

**Comment by cubei** [comment]
I have created a release. Anything else I need to do?

**Comment by IzzySoft** [comment]
Thanks a lot! For my repo that's all what's needed (just [added your app](https://apt.izzysoft.de/fdroid/index/apk/com.quchen.flashcard)). I take it you'd agree to have it in the official repo? Then I'd take the necessary steps.

**Comment by cubei** [comment]
Yes, you can do so.
So in the future I just create a release on github from time to time?

**Comment by IzzySoft** [comment]
Thanks! Opened the corresponding [RFP here](https://gitlab.com/fdroid/rfp/issues/770) (RFP = Request For Packaging).

And yepp, exactly. My auto-updater fetches the attached APK within 24h. It's important the tag name corresponds to `versionName` (which it currently does not; could you please create a new tag matching this, and then stick to that naming convention? Thanks!), or a new version cannot be detected correctly (neither by my updater, nor by F-Droid's).

**Comment by cubei** [comment]
So my manifest/gradle states version "1.2.1". The tag on Github is now "v1.2.1", is the 'v' prefix correct or should it be removed?

Edit: I added the 'v' prefix to the apk as well

**Comment by IzzySoft** [comment]
The `v` prefix in the tag name is optional, but it should not be present in the `versionName`. And ugh, the gradle behind tag v1.2.2 reports version 1.2.1 – same as tag v1.2.1? Funnily, the APK has `1.2.2` as `versionName` – but still the same `versionCode` as v1.2.1 (which doesn't work, as that's what versions are identified by internally – so the two look like the very same version).

Meanwhile our bot scanned your repo and gave a thumbs-up. It encountered an "insecure gradlew" nevertheless which you might wish to take a look at (doesn't affect F-Droid as we don't pull that way).
