### ISSUE TITLE
Option to delete

### ISSUE THREAD

**Issue by haseebpvt** [cubei/flashcards#14]
Option to delete folder and csv files

**Comment by cubei** [comment]
This is planned for a long press of a list item.
At the moment it can be done manually as workaround by deleting the folder or file on the storage under Android/data/com.quchen.flashcard/cache/lists
Also the cache folder is probably not the best one for persistent data.

**Comment by cubei** [comment]
Long press to delete was implemented with commit d73ffcef8775112eb1e4264e8f100f39ede35172
