### ISSUE TITLE
Read the words (Voice output for pronunciation)

### ISSUE THREAD

**Issue by niccokunzmann** [cubei/flashcards#24]
Especially with Chinese or maybe with other languages, too, I have no idea how to pronounce them.
Wikitionary has free sound files which could be retrieved.
Example: DE-EN "no"/"nein" - https://en.wiktionary.org/wiki/nein 
Here, I would like to discuss how to implement this and if this is open to be implemented.

**Comment by cubei** [comment]
I'm not sure how this would work with wiktionary files. An internet connection is needed and if a phrasem instead of a single word is used, it would be difficult and conjugations of words are not available it seems.
If I would do such a feature, I would simply use the Android TextToSpeech function.

**Comment by niccokunzmann** [comment]
Oh, I did not think about the text-to-speech engine. It probably is
well-suited for easy phrases. Especially those used many times. One
would need to see if that is true and maybe if additional packages need
to be installed to make it work in the corresponding languages.
Thanks for replying!

**Comment by cubei** [comment]
Text to speech support with commit d5e65c7292262b94c35024f107ecbd0eb20cb317
